version: '3'
services:
  server:
    restart: unless-stopped
    build: .
    environment:
      GATEWAY_URL: http://echo-server
      PORT: 4343
    ports:
      - '4343:4343'
  echo-server:
    image: mendhak/http-https-echo
    ports:
      - '5353:80'

